### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by julesmoretti** [raymondchooi/testPagingEnabled#1]
@raymondchooi - I tried installing this and got the following errors:

```
Starting JS server...
Running /Users/jmoretti/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:25972) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
(node:25972) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Steps I took to get there:
```
npm i
react-native run-android
```

some context:
node v7.10.0

├── babel-jest@18.0.0
├── babel-preset-react-native@1.9.1
├── jest@18.1.0
├── react@15.4.2
├── react-native@0.40.0
└── react-test-renderer@15.4.2

Thank you for your help with this.

**Comment by julesmoretti** [comment]
@raymondchooi - any update with this?

**Comment by raymondchooi** [comment]
@julesmoretti did you fork the pull request and change the settings to build from source?

https://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by julesmoretti** [comment]
@raymondchooi - thank you for your response.

I got cloned this repo and then did the above two steps only "npm i..."

Could you give me the steps that I should run locally for a proof that pagination work vertically on Android?

Ideally using a simulator.

Thank you very much.

**Comment by raymondchooi** [comment]
I should have added the commands to not remove the changed files when I pushed to github. I'll look into that when I have some time.

For now, to test you can follow the link I sent above but when you get to '1. Installing the fork' step, clone the last commit in the pull request: https://github.com/facebook/react-native/tree/0c92154c65b76940f4619f0a61db73bf3960b0a9 

After this, the app should build from the changed files instead of the default cached. This app is just a few different coloured pages with scrollview. You can use this as the base app to carry out the above steps or just copy and paste the code in App.js to test.

**Comment by julesmoretti** [comment]
@raymondchooi - Thank you for your response. My expectation is that I should just be able to run it over simulator to validate the behavior.

So based on my expectation and your comments above this is what I did:
```
npm install --save github:facebook/react-native#0c92154c65b76940f4619f0a61db73bf3960b0a9
watchman watch-del-all
rm -Rf ios
rm -Rf android
rm -Rf node_modules
rm -fr $TMPDIR/react-*
npm i
react-native upgrade
react-native android
```

At this point I expect to have a clean install of your demo file and should be able to experience the new behavior without any issues.

But then when running `react-native run-android` this is what I get stuck with:

```
:app:generateDebugSources
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/Users/jmoretti/Git/testPagingEnabled/android/app/src/main/java/com/testpagingenabled/MainApplication.java:6: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
/Users/jmoretti/Git/testPagingEnabled/android/app/src/main/java/com/testpagingenabled/MainApplication.java:8: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
/Users/jmoretti/Git/testPagingEnabled/android/app/src/main/java/com/testpagingenabled/MainApplication.java:16: error: cannot find symbol
public class MainApplication extends Application implements ReactApplication {
                                                            ^
  symbol: class ReactApplication
/Users/jmoretti/Git/testPagingEnabled/android/app/src/main/java/com/testpagingenabled/MainApplication.java:18: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/jmoretti/Git/testPagingEnabled/android/app/src/main/java/com/testpagingenabled/MainApplication.java:33: error: cannot find symbol
  public ReactNativeHost getReactNativeHost() {
         ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/jmoretti/Git/testPagingEnabled/android/app/src/main/java/com/testpagingenabled/MainActivity.java:5: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity
public class MainActivity extends ReactActivity {
       ^
/Users/jmoretti/Git/testPagingEnabled/android/app/src/main/java/com/testpagingenabled/MainApplication.java:18: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                       ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/jmoretti/Git/testPagingEnabled/android/app/src/main/java/com/testpagingenabled/MainApplication.java:32: error: method does not override or implement a method from a supertype
  @Override
  ^
8 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.055 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

Let me know if I am missing anything here.

Thank you.

**Comment by raymondchooi** [comment]
You need to make sure you can build from source: https://facebook.github.io/react-native/docs/android-building-from-source.html 

Make sure you follow all the instructions in the link. That error probably means your environment variables aren't setup to build from source.

**Comment by julesmoretti** [comment]
@raymondchooi thank you!

Ok tried to follow the link information but still do not get any successful result:

So this is what I did so far:
Made sure the prerequisite are true.

In my .zshrc file

```
# Add Android Studio
export ANDROID_HOME=~/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools/adb
export ANDROID_SDK=/Users/jmoretti/Library/Android/sdk
export ANDROID_NDK=/Users/jmoretti/android-ndk-r10e
```

In a new local.properties

```
sdk.dir=/Users/jmoretti/Library/Android/sdk
ndk.dir=/Users/jmoretti/android-ndk-r10e

```

downloaded the NDK and extracted it at `/Users/jmoretti/android-ndk-r10e
`

For the `1. Installing the fork` point I kept using the `npm install --save github:facebook/react-native#0c92154c65b76940f4619f0a61db73bf3960b0a9` so that the package.json file looks like this:

```
{
  "name": "testPagingEnabled",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-native": "github:facebook/react-native#0c92154c65b76940f4619f0a61db73bf3960b0a9"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.1.0",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Then the other steps were already in your repo except for the following which I added to the bottom of the `android/app/build.gradle` file:

```
configurations.all {
    exclude group: 'com.facebook.react', module: 'react-native'
}
```

Rebuilt the node_modules folder by deleting it and doing `npm i`

Then I did `react-native run-android` and got this:

And this is what I get:
```
> testPagingEnabled@0.0.1 android /Users/jmoretti/Git/testPagingEnabled
> react-native run-android

Starting JS server...
Running /Users/jmoretti/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

What am I missing?

**Comment by raymondchooi** [comment]
I'm not really sure from that. You could try to build from the react native master source to check if it's a problem with your setup (It should take a lot longer to build). If it works, you can edit the files like in the commits and build again.

**Comment by julesmoretti** [comment]
@raymondchooi - ok so I did a new repo following https://facebook.github.io/react-native/docs/android-building-from-source.html and this is what we got:

```
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:transformClassesWithDexForDebug
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug
:app:transformNative_libsWithStripDebugSymbolForDebug
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug
:app:installDebug
Installing APK 'app-debug.apk' on '5.1_WVGA_API_25_-_Kiki(AVD) - 7.1.1' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 2 mins 39.699 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
Running /Users/jmoretti/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (/Users/jmoretti/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -n com.testpagingjules/.MainActivity)...
Starting: Intent { cmp=com.testpagingjules/.MainActivity }
```

Now if I delete `"react-native": "^0.44.0"` from the `package.json` file and run:

```
npm i --save github:facebook/react-native#0c92154c65b76940f4619f0a61db73bf3960b0a9
```
and then:

```
react-native run-android
```

I get:

```
:ReactAndroid:incrementalReleaseJavaCompilationSafeguard
:ReactAndroid:createNativeDepsDirectories UP-TO-DATE
:ReactAndroid:downloadBoost FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:downloadBoost'.
> javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.952 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```
